version: 2.1
jobs:
  build:
    docker:
      - image: node:16-alpine
        environment:
          TERM: xterm
          TZ: "America/New_York"

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install

      - run:
          name: Unit Test
          command: yarn test
